[package]
name = "tarpaulin_fails"
version = "0.1.0"
authors = ["parallels"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.ressa]
git = "ssh://git@github.com/rusty-ecma/ressa.git"

